### PR TITLE
fix: update path rewrite

### LINKED ISSUE #727: Renku v2 says "no access" for public code repositories
See https://swiss-data-science.slack.com/archives/C67N59QL8/p1727165108839549

image

From user: 
> In my demo project, I have 2 public code repos, one from the Renku GitLab and one from GitHub, yet they say “no access”.

https://renkulab.io/v2/projects/renku-team/n2o-pathway-analysis

on renku 0.57.1

### PR DESCRIPTION
**Pull request by leafty**
Fixes #727.

/deploy

### CODE REVIEW

File: internal/revproxy/main_test.go [hunk 1]
```diff
@@ -963,6 +963,13 @@ func TestInternalSvcRoutes(t *testing.T) {
 			Path:     "/api/kc/auth/realms/Renku/protocol/openid-connect/userinfo",
 			Expected: TestResults{Path: "/auth/realms/Renku/protocol/openid-connect/userinfo", VisitedServerIDs: []string{"upstream"}},
 		},
+		{
+			Path: "/ui-server/api/data/repositories/https%3A%2F%2Fexample.org%2Fgroup%2Frepo",
+			Expected: TestResults{
+				Path:            "/api/data/repositories/https%3A%2F%2Fexample.org%2Fgroup%2Frepo",
+				VisitedServerIDs: []string{"upstream"},
+			},
+		},
```
Comment (leafty) [inline internal/revproxy/main_test.go:972]: Note that this test case fails prior to the fix.

**Review by olevski — APPROVED** [review]
